Least squares intersection point and line fitting -- advanced. Equation (2.4) shows how the intersection of two 2D
lines can be expressed as their cross product, assuming the lines are expressed as homogenous coordinates.

1. If you are given more than two lines and want to find a point $\tilde{x}$ that minimizes the sum of squared distances to
each line, $$\displaystyle D = \sum_{i}(\tilde{x} \cdot \tilde{l}_i)^2$$ how can you compute this quantity? (Hint: Write the dot product as
$\tilde{x}^T\tilde{l}_i$, and turn the squared quantity into a quadratic form, $\tilde{x}^TA\tilde{x}$.)

In [1]:
%cd /home/ubuntu/CV-Algs-Apps-2ED

import numpy as np

from src.primitives.point import Point2D
from src.primitives.line import Line2D

/home/ubuntu/CV-Algs-Apps-2ED


In [196]:
import importlib
from src.primitives import line, point
importlib.reload(line)
importlib.reload(point)

<module 'src.primitives.point' from '/home/ubuntu/CV-Algs-Apps-2ED/src/primitives/point.py'>

In [199]:
# Test the classes first

point1 = Point2D(3.0, 1.0, 1.0)
print(f"p1: {point1}")
point2 = Point2D(-4.0, 5.0, 1.0)
print(f"p2: {point2}")
line1 = Line2D(p1=point1, p2=point2)
print(f"line1: {line1}")
contains = line1.contains_point(point1)
print(f"{line1} contains {point1} = {contains}")
assert contains

print("\n")
line2 = Line2D(a=1.0, b=-7.0, c=8.0)
print(f"line2: {line2}")
line3 = Line2D(a=3.0, b=-4.0, c=1.0)
print(f"line3: {line3}")
inter = line2.intersection_with(line3)
print(f"inter: {inter}")
assert inter == Point2D(25.0, 23.0, 17.0)


p1: Point2D([3. 1. 1.])
p2: Point2D([-4.  5.  1.])
line1: Line2D([-4. -7. 19.])
Line2D([-4. -7. 19.]) contains Point2D([3. 1. 1.]) = True


line2: Line2D([ 1. -7.  8.])
line3: Line2D([ 3. -4.  1.])
inter: Point2D([25. 23. 17.])


In [208]:

query_p = Point2D(3.0, 1.0, 1.0)

line1 = Line2D(a=6.0, b=4.0, c=1.0)
line2 = Line2D(a=-3.0, b=2.0, c=1.0)
line3 = Line2D(a=4.0, b=7.0, c=1.0)

def dot_prod(p: Point2D, l: Line2D) -> float:
    return np.dot(p.vector.T, l.vector)

def squared_quantity(p: Point2D, l: Line2D) -> float:
    dp = dot_prod(p, l)
    return dp * dp

L = np.array([line1.vector, line2.vector, line3.vector])
print(f"L: {L}")
A = np.dot(L.T, L)
print(f"A: {A}")


dp_res = dot_prod(query_p, line1)
print(f"dp_res: {dp_res}")
sq_res = squared_quantity(query_p, line1)
print(f"sq_res: {sq_res}")

def quad_form(p: Point2D, A: np.ndarray):
    return np.dot(p.vector.T, np.dot(A, p.vector))

answer = quad_form(query_p, A)
print(f"query point distance: {answer}")


# A_pseudo_inv = np.linalg.pinv(A)
# # Find point that minimizes distances
# minimized_point = np.dot(A_pseudo_inv, np.zeros(3))
# print(f"minimum point: {minimized_point}")

    

L: [[ 6.  4.  1.]
 [-3.  2.  1.]
 [ 4.  7.  1.]]
A: [[61. 46.  7.]
 [46. 69. 13.]
 [ 7. 13.  3.]]
dp_res: 23.0
sq_res: 529.0
query point distance: 965.0
minimum point: [0. 0. 0.]


In [4]:
v1 = np.array([1, 2, 3])
print(v1.shape)
print(v1.T.shape)

(3,)
(3,)
